### ISSUE TITLE
js/crypto unavailable in nodejs

### ISSUE THREAD

**Issue by knubie** [zelark/nano-id#14]
nano-id uses `window.crypto`, but that object is not defined in nodejs.

https://github.com/zelark/nano-id/blob/1467b6a0e9a36a73484463b5071655f0d30b55c1/src/nano_id/random.cljc#L7-L9

**Comment by zelark** [comment]
I will look at it soon, thanks for reporting.

**Comment by zelark** [comment]
@knubie sorry, I was away for a while. Do you still need support for nodejs?

**Comment by knubie** [comment]
@zelark No problem. I was able to resolve the issue by using this polyfill: [@peculiar/webcrypto](https://www.npmjs.com/package/@peculiar/webcrypto). I'm not sure this library should add any more dependencies, so I'm satisfied with that workaround.

**Comment by zelark** [comment]
@knubie thanks for sharing, I think I need to add an example to README.

**Comment by zelark** [comment]
Added an example https://github.com/zelark/nano-id#nodejs
