### ISSUE TITLE
API 2.0

### ISSUE THREAD

**Issue by ai** [zelark/nano-id#7]
Let’s update the library to be compatible with the latest Nano ID 2.0:

- [ ] Replace `~` to `-` in default alphabet
- [ ] Add `non-secure` fast generator
- [ ] Async API?

**Comment by zelark** [comment]
Sorry, I'm busy now, I'll answer you at weekend.

**Comment by zelark** [comment]
Thanks for looking after the forks. It's really nice!

I don't mind the first item.
The second one looks like: If someone needs it, they could reach it with ease, just using `java.util.Random`. Thus, I don't think we need it out-of-the-box.
And about the third one, I have nothing to say right now.

**Comment by zelark** [comment]
If someone wants to pick this issue, fix only the first item.
